@startuml ArtworkTag_Class_Diagram
skinparam backgroundColor #F5F5F5
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #333333
skinparam classArrowColor #333333
skinparam classAttributeIconSize 0

class ArtworkTag {
    - name: String
    ---
    + ArtworkTag()
    + ArtworkTag(name)
    + getName(): String
    + setName(name): void
    + toString(): String
}

@enduml

